version: '2.1'
services:   
    flask-server:    
        restart: always    
        build: .    
        ports:      
            - 5000:5000  
        volumes:      
            - .:/app
        environment:
            - DEBUG=1